### ISSUE TITLE
diseño de la web

### ISSUE THREAD

**Issue by jesusantguerrero** [andreumas/DAWtrimestrenum2#1]
por aqui estáré subiendo los archivos bro

**Comment by jesusantguerrero** [comment]
##Hover en las imagenes, centrado de la página, uso de flexbox en vez de float

Bueno mira, solo le agregué un efecto a cada imagen, centré la pagina  y le puse un backgound para que no se vea muy cargada, le di el mismo tamaño a todas las imagenes, lo demas lo deje todo como estaba, si quieres algun cambio solo me dices y lo hacemos, y de ahí puedes guiarte para hacer las otras páginas:


 ## Codigo html:

``` html 
<!DOCTYPE html>
<html>

<head>
  <link rel="stylesheet" type="text/css" href="estilos.css">
  <title>L Video Games</title>
</head>

<body background="img/fondo.jpg">

  <header>
    <img class="logo2" SRC="img/logo.jpg"/>
    <!--<h2 class="brand">L Video Games</h2>-->


    <nav id="navegador">
      <ul>
        <li><a class="active" href="/index.html">Index</a></li>
        <li><a href="/Minecraft">Minecraft</a></li>
        <li><a href="/fifa">FIFA 17</a></li>
        <li><a href="/clash">Clash of Clans</a></li>
      </ul>
    </nav>
  </header>


  <div id="banner">
    <IMG class="imgbanner" SRC="img/banner3.png">

  </div>

  <section class="seccion-principal" id="section1">
    <aside id="publiizquierda">
      <h2 class="titulo">Titulo de este aside</h2>
     <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa.

     </p>

     <p>Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.
        Aenean vulputate eleifend tellus. Aenean leo ligula,
        porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,
    </p>

    <p>Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.
        Aenean vulputate eleifend tellus. Aenean leo ligula,
        porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a,
    </p>
    
    </aside>

    <div id="contenido">
      <article background="img/fondo.jpg" class="articulos" id="articulos1">

        <div class="item-card">
          <IMG class="item-img" SRC="img/mine1.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>
        
        <div class="item-card">
          <IMG class="minebanner2 item" SRC="img/mine2.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>

        <div class="item-card">
          <IMG class="minebanner3 item" SRC="img/mine3.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>


      </article>

      <article background="img/fondo.jpg" class="articulos" id="articulos2">
        
        <div class="item-card">
          <IMG class="fifabanner item" SRC="img/fifa1a.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>

        <div class="item-card">
          <IMG class="fifabanner2 item" SRC="img/fifa2a.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>

        <div class="item-card">
          <IMG class="fifabanner3 item" SRC="img/fifa3a.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>

      </article>

      <article background="img/fondo.jpg"  class="articulos" id="articulos3">

        <div class="item-card">
          <IMG class="clanbanner item" SRC="img/clashroyale1a.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>

        <div class="item-card">       
          <IMG class="clanbanner2 item" SRC="img/clashroyale2a.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>

        <div class="item-card">        
          <IMG class="clanbanner3 item" SRC="img/clashroyale3a.jpg">
          <h2 class="titulo"> Nombre Del Articulo</h2>
          <div class="cover"></div>
        </div>
        
      </article>
    </div>
  </section>


  <footer>
    <article id="logo">LOGO</article>
    <article id="copy"></article>


  </footer>
</body>

</html>
```

## Codigo CSS:

``` css

*{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif
}
body{
padding: 0 2%;
}
  
.brand{
  color: #f1f1f1;
  font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif
}

/* Estos son los estilos de los items de las imagenes*/

.item-card{
  height: 205px;
  width: 32%;
  border-radius: 8px;
  border: 1px solid #ccc;
  overflow: hidden;
  position: relative;
  cursor: pointer;
  transition: all ease .3s;
  opacity: .8;
}

.item-card:hover{
  border: 1px solid #aaa;
  box-shadow: 0px 2px 4px rgba(0,0,0,.4);
  opacity: 1;
}

.item-card img{
  height: 100%;
  width: 100%;
}

.item-card .titulo{
  position: absolute;
  height: 30%;
  width: 100%;
  text-align: center;
  padding: 5% 0;
  background: rgba(0,0,0,.6);
  bottom: 0;
  left: 0;
  color: #f1f1f1;
  transition: all ease .3s
}

.item-card:hover .titulo{
  height: 100%;
  width: 100%;
}
/* finalizando los estilos de los items de las imagenes*/

.navegador{

color:white;
float:top;
position:top;
margin-top: 0px;
height: 50px;
width: 100%;
}

 ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    border: 1px solid #e7e7e7;
    background-color: #FA5858;
}

li {
    float: left;
}

li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
}

li a:hover:not(.active) {
    background-color: red;
}

li a.active {
    color: white;
    background-color: red;
}
   


.imgbanner{
height:209px;
width:100%;

}

#banner{

    height: 200px;
    padding-bottom: 15px;

       
}

#minebanner{
height: 200px;
width: 95%;
float:right;
}

#minebanner2{
height: 205px;
width: 98%;
float:center;
}

#minebanner3{
height: 205px;
width: 98%;
float:left;
}

#fifabanner{
height: 195px;
width: 95%;
float:right;
}

#fifabanner2{
height: 205px;
width: 98%;
float:center;
}

#fifabanner3{
height: 200px;
width: 98%;
float:left;
}

/* Estilos del Aside */
#publiizquierda{
    min-height: 100vh;
    width: 19.5%;
    margin: 0 .5% 0 0;
    padding: 20px 10px;
    background-color: #f20;    
}

#publiizquierda .titulo{
  color: #f1f1f1;
  margin: 0 0 30px 0;
}

#publiizquierda p{
  color: #ccc;
  margin: 20px 0;
}


/* Estilos del Aside */

.seccion-principal{
  width: 100%;
  display: flex;
  justify-content: space-between;
  margin: 50px 0 10px 0;
  background: #f1f1f1;
}

#contenido {
margin:0 7px 7px 7px 7px;  width: 75%;
float: left; 
width: 80%;
min-height: 100vh;
}

#contenido .item{


}

.articulos{
  display: flex;
  justify-content: space-around;
  width: 100%;
  margin: 3px 0
}

#articulos1{
	border-width:1px; 
	color:white;
  background-image: url("img/.jpg");
}

#articulos2{

	
	border-width:1px;
  background-image: url("img/.jpg");
}

#articulos3{

	
	border-width:1px; 
    background-image: url("img/.jpg");
}

footer {
	height: 100px;
	background-color: #333;
	clear: both;
  color: #fff;
  padding: 10px 15px
}


#logo2{
	width:25px;
	height:25px;
position:fixed;
}

#copy{



}
```
